"""Only autogenerated content"""
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
    raise RuntimeError(
        "This package is not meant to be used at runtime. "
        "Please, import from 'shhell' package instead of 'shhell._executables'."
    )
